development:
  access_key_id: "AKIAI6L6SPEJCRL7MGPQ"
  secret_access_key: "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"
  bucket: "trialtask"
test:
  access_key_id: "AKIAI6L6SPEJCRL7MGPQ"
  secret_access_key: "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"
  bucket: "trialtask"
production:
  access_key_id: "AKIAI6L6SPEJCRL7MGPQ"
  secret_access_key: "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"
  bucket: "trialtask"  
  
# heroku config:set AWS_ACCESS_KEY_ID=AKIAI6L6SPEJCRL7MGPQ AWS_SECRET_ACCESS_KEY=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
# heroku config:set S3_BUCKET_NAME=trialtask
